---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos8
    image: f1tz/centos8mirrorfix:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
