---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos8
    dockerfile: Dockerfile.j2
    image: docker.io/pycontribs/centos:8
    pre_build_image: false
  - name: debian
    image: python:3.8.14-bullseye
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
